//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIBLIOTECA2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BIBLIOTECA2Entities : DbContext
    {
        public BIBLIOTECA2Entities()
            : base("name=BIBLIOTECA2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BIBLIOTECA> BIBLIOTECAs { get; set; }
        public virtual DbSet<LIBRO> LIBROes { get; set; }
        public virtual DbSet<USUARIO> USUARIOs { get; set; }
    }
}
